- name: Install MongoDB GPG key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0C49F3730359A14518585931BC711F9BA15703C6 state=present

- name: Add MongoDB source list
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/{{mongodb_version}} multiverse' state=present

- name: Install dependencies
  apt: pkg={{item}} state=latest update_cache=true
  with_items:
    - mongodb-org
    - mongodb-org-tools

- name: Deploy systemd script
  template:
    src=mongod.service.systemd.j2
    dest=/etc/systemd/system/mongod.service
    mode=0644
  notify:
    - Reload systemd

- name: Deploy MongoDB configuration
  template:
    src=mongod.conf.j2
    dest=/etc/mongod.conf
    mode=0644
  notify:
    - Restart MongoDB

- name: Ensure MongoDB is started
  action: service name=mongod state=started
