- name: Update Apt cache
  apt: update_cache=true cache_valid_time=3600

- name: Install dependencies
  apt: pkg={{item}} state=present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Install Docker GPG key
  apt_key: keyserver=hkp://ha.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: Add Docker Apt repository
  apt_repository: repo="deb https://apt.dockerproject.org/repo {{ansible_distribution|lower}}-{{ansible_distribution_release}} main" state=present

- name: Install Docker package
  apt: name=docker-engine state=present
  notify:
    - Reload systemd
    - Restart Docker

- name: Change user group
  user: name={{ansible_user}}
        groups=docker
        append=yes

- name: Ensure Docker is started
  service: name=docker state=started
