- name: Reload systemd
  command: systemctl daemon-reload

- name: Restart Consul Template
  action: service name=consul-template state=restarted enabled=true

- name: Reload Consul Template
  service: name=consul-template state=reloaded

- name: Remove Consul Template archive
  file:
    path={{consul_template_download_path}}
    state=absent
    force=true
